---
abstract: 'Catalyst Model providing access to the L<WebService::MyGengo> library'
author:
  - 'Nathaniel Heinrichs'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Getopt::Long: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Model-WebService-MyGengo
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Model::Adaptor: 0.10
  WebService::MyGengo: 0.010
  namespace::autoclean: 0
  perl: 5.8.4
resources:
  license: http://dev.perl.org/licenses/
version: 0.002
